### PR TITLE
fix #493 - SemiStructuredNodes can have no props at it's class definition

### LINKED ISSUE #493: SemiStructuredNode can't have no props
I have this class:

```python3
class Metadata(SemiStructuredNode):
    pass
```

if i try:
```python3
m = Metadata()
m.foo = 'bar'
m.save()
```

the app crashes with:
  File "<my-path>/env/lib/python3.8/site-packages/neomodel/contrib/semi_structured.py", line 45, in inflate
    for free_key in (x for x in node_properties if x not in props):
UnboundLocalError: local variable 'node_properties' referenced before assignment

this can be fixed by initializing node_properties:

```python3
    @classmethod
    def inflate(cls, node):
        # support lazy loading
        if isinstance(node, int):
            snode = cls()
            snode.id = node
        else:
            props = {}
            node_properties = {}  # Please, assign this variable!
            for key, prop in cls.__all_properties__:
                node_properties = _get_node_properties(node)
                if key in node_properties:
                    props[key] = prop.inflate(node_properties[key], node)
                elif prop.has_default:
                    props[key] = prop.default_value()
                else:
                    props[key] = None
            # handle properties not defined on the class
            for free_key in (x for x in node_properties if x not in props):
                if hasattr(cls, free_key):
                    raise InflateConflict(cls, free_key,
                                          node_properties[free_key], node.id)
                props[free_key] = node_properties[free_key]

            snode = cls(**props)
            snode.id = node.id

        return snode
```
add this code `node_properties = {}` on line 36

### PR DESCRIPTION
**Pull request by dmp593**

### CODE REVIEW

**Comment by whatSocks** [comment]
@dmp593 could you add a unit test for this use case?

**Comment by MattGalvis** [comment]
@dmp593 could you add a unit test for this use case?

**Comment by dmp593** [comment]
@whatSocks and @MattGalvis unit test added!
Sorry, @whatSocks I completely missed your comment in august 2020.

**Comment by whatSocks** [comment]
will test

**Comment by whatSocks** [comment]
merged, thanks @dmp593

**Pull request merged**
