### PR TITLE
Add support for multi databases

### PR DESCRIPTION
**Pull request by mRoca**
Resolve https://github.com/neo4j-contrib/neomodel/issues/526

Driver database documentation: https://neo4j.com/docs/api/python-driver/4.1/api.html#database

With this PR, we can specify the database name in the neo4j or bolr URL:

`bolt://neo4j:neo4j@localhost:7687` => default database
`bolt://neo4j:neo4j@localhost:7687/mydb` => `mydb` database

### CODE REVIEW

**Comment by mRoca** [comment]
It would be easier to avoid the new ENV variable, and allowing to pass the DB name into the url: `bolt://neo4j:neo4j@localhost:7687/mydb`, for instance.

=> What do you think about that ?

**Comment by nossila** [comment]
It looks good to me.

> It would be easier to avoid the new ENV variable, and allowing to pass the DB name into the url: bolt://neo4j:neo4j@localhost:7687/mydb, for instance.

I like the idea a lot, but seems like this is something to be done on neo4j-driver instead. But I'd say lets use your solution now

**Comment by mRoca** [comment]
> It looks good to me.
> 
> > It would be easier to avoid the new ENV variable, and allowing to pass the DB name into the url: bolt://neo4j:neo4j@localhost:7687/mydb, for instance.
> 
> I like the idea a lot, but seems like this is something to be done on neo4j-driver instead. But I'd say lets use your solution now

If we only use the `config.DATABASE_URL = 'bolt://neo4j:neo4j@localhost:7687/mydb'` syntax, the solution would be more flexible, as we won't have to update all related packages (as `django-neomodel` for instance): updating the connection string will be enough to use this features, without having to create another PR with the new `DATABASE_NAME` config var to handle.

**Comment by nossila** [comment]
@mRoca actually I think it makes a lot of sense to have the database in the URL like you suggested, I was under the impression that the URL parsing was done by the `neo4j-driver` but turns out it is not :P https://github.com/neo4j-contrib/neomodel/blob/bfeae3e10498006dc0aae6bab2885a3c0f194dc3/neomodel/util.py#L90

**Comment by mRoca** [comment]
I've reworked this PR. Now, the database is extracted from the url: `bolt://neo4j:neo4j@localhost:7687/mydb` if provided.

`bolt://neo4j:neo4j@localhost:7687` still works, with the default database.

**Comment by mRoca** [comment]
@nossila What do you think about this new version?

Who can review this PR?

**Pull request merged**
