### PR TITLE
Add support for bookmarks in transactions

### PR DESCRIPTION
**Pull request by kupuguy**
This pull request adds support for Neo4J bookmarks in both decorated transactions and explicit transactions.

### CODE REVIEW

**Comment by aanastasiou** [comment]
@kupuguy Thank you very much, that's great, I will try to take a closer look as soon as possible.

**Comment by aanastasiou** [comment]
@robertlagrant , @mvanderkroon Can I please ask you to have a look through this commit, in case it also deals with [this issue](https://github.com/neo4j-contrib/neomodel/issues/335) too?

**Comment by robertlagrant** [comment]
@aanastasiou Hi - I don't think they're related. This seems like a good step forward, but on a different front.

**Comment by mvanderkroon** [comment]
@aanastasiou I agree with @robertlagrant, not related by the look of it. Still a nice move forward though.

**Comment by oaudry** [comment]
hello

many thx for this PR. Any chance to see it merged ? 

oau

**Comment by whatSocks** [comment]
@kupuguy it's been a while, but if you're still interested in this PR we would be happy to test it. Would it be possible for you to rebase and run tests?

**Pull request merged**
