### PR TITLE
Explicit write transaction mode

### PR DESCRIPTION
**Pull request by robertlagrant**
Causal clustering has a leader and multiple followers. Only leader can be written to.

Initiating a transaction with `@db.transaction` doesn't seem to allow the specifying of a transactionality type (Bolt is READ or WRITE), thus it's possible that the `bolt+routing` protocol could route a write transaction to a follower.

This PR allows the developer to choose `@db.write_transaction`, which will set `access_mode` to `"WRITE"`, directing Bolt to the leader of a causal cluster. It defaults to the previous behaviour to avoids backwards compatibility issues.

### CODE REVIEW

**Comment by robertlagrant** [comment]
This is to address issue #335

**Comment by robertlagrant** [comment]
@robinedwards no problem - I've added a bit of documentation; let me know what you think.

**Comment by robinedwards** [comment]
This great, really appreciate it @robertlagrant

**Comment by robertlagrant** [comment]
@robinedwards it's a pleasure! Is there a release scheduled for some time soon? I'm trying to figure out if I need a custom build or not.

**Comment by robinedwards** [comment]
Released!

**Pull request merged**
