### PR TITLE
Added support for Q() in filter and exclude .

### PR DESCRIPTION
**Pull request by juanmhidalgo**
Implemented Q() filter and exclude like Django.
(Filter with OR #332)

### CODE REVIEW

**Comment by juanmhidalgo** [comment]
I modified tree.py to force CI to run the tests again.
It would be great if you can review this.

**Comment by robinedwards** [comment]
Hey thank you for this its a really useful feature. Can I request that the `Node` class that's borrowed from Django is renamed as people could potentially find this confusing. Perhaps just merge the methods into Q or name it something like QBase?

**Comment by robinedwards** [comment]
Also rename the tree package to `match_q.py` or something similar

**Comment by juanmhidalgo** [comment]
@robinedwards Done.

**Comment by robinedwards** [comment]
Thank you thats brilliant!

**Comment by robinedwards** [comment]
Sorry one last request would you be able to add a few example queries in https://github.com/neo4j-contrib/neomodel/blob/master/doc/source/queries.rst so other people are aware of the feature?

**Comment by juanmhidalgo** [comment]
@robinedwards 
The documentation is ready. I took the Django documentation for Q objects and modified a little bit.

**Comment by robinedwards** [comment]
Thnk you @juanmhidalgo !

**Pull request merged**
