### PR TITLE
fix creating a semi structured node with optional values omitted

### PR DESCRIPTION
**Pull request by EricAtORS**
I was trying to create a semi structured node with only the required values present and it would fail. 
This PR fixes it.
I've added a test to demonstrate the use case I have.

### CODE REVIEW

**Comment by aanastasiou** [comment]
Thanks @EricAtORS , will have a look shortly. Just out of curiosity, can you please post the minimal example that was failing?

**Comment by aanastasiou** [comment]
@EricAtORS Can you please describe the error you were getting? (I am getting an error indeed, but I would like us to confirm that we are talking about the same thing).

**Comment by EricAtORS** [comment]
@aanastasiou 
I hadn't seen the udpated, but just in case you still need it:
```
  File "...\lib\site-packages\neomodel\contrib\semi_structured.py", line 61, in deflate
    raise DeflateConflict(cls, key, deflated[key], obj.id)
KeyError: 'description'
```

**Review by mariusconjeaud — APPROVED** [review]

**Comment by EricAtORS** [comment]
@mariusconjeaud 
Thank you!

**Pull request merged**
