### PR TITLE
Handle db passwords with special chars

### PR DESCRIPTION
**Pull request by amikrop**
When a database password contains some "special characters", like "?", it causes `set_connection` to raise an exception (URL parsing fails). This pull request url-quotes the password before the parsing, then url-unquotes it.

### CODE REVIEW

**Review by nossila — APPROVED** [review]

**Comment by whatSocks** [comment]
thank you @amikrop !

**Comment by amikrop** [comment]
> thank you @amikrop !

You 're welcome!

**Comment by whatSocks** [comment]
do you need a release ASAP @amikrop ?
I would like to address some other issues first (like #567)

**Comment by amikrop** [comment]
> do you need a release ASAP @amikrop ?
> I would like to address some other issues first (like #567)

It's ok, take your time.

**Pull request merged**
