### PR TITLE
Fix for #487

### PR DESCRIPTION
**Pull request by JVemmer**
As requested by @aanastasiou in #487, here is a fix for the param issue. Only explicit traversal seems to not work, but I have not focused on that, since it seems separate from the param issue (also possible that I simply do not understand it).
The following things were tested:
- [x] .get()
- [x] .save()
- [x] .filter()
- [x] .delete()
- [x] .refresh()
- [x] lazy evaluation (lazy=True)
- [x] property reference (n.id)
- [x] retrieving related nodes (n.friends_with.all())
- [ ] relationship connection (n.friends_with.connect(m)) - Does not work due to #488.
- [x] .exclude() (n.friends_with.exclude(name='test2'))
- [x] relationship disconnect (n.friends_with.disconnect(m) + n.friends_with.disconnect_all())

### CODE REVIEW

**Comment by aanastasiou** [comment]
@JVemmer 

Thanks for taking the time to work on these issues. Unfortunately, on my setup, I get a number of test failures due to errors with constraints.

I can see that you have requested me to review these changes. But there is a huge amount of checks that is performed by the tests themselves. Once you have made a change, please run the tests and the errors (or sometimes messages) originating from those tests will let you know what might be going wrong, *even though the code might appear to work as expected for certain functionality*.

This was the reason I asked if you could try running the tests a few weeks ago.

Now, I cannot run the tests on my setup (still looking into it), but looking at [the output of the tests that run automatically upon submitting a PR](https://travis-ci.org/neo4j-contrib/neomodel/jobs/652447970?utm_medium=notification&utm_source=github_status), I can see the following:

```
self = <neobolt.direct.Response object at 0x7fa82c6c3e10>
metadata = {'code': 'Neo.ClientError.Statement.ParameterMissing', 'message': 'Expected a parameter named nodeid'}
```

This occurs within `test_relationship_models.py`.

Can I please ask you to have another look at the substitutions you did and check if, perhaps mistakenly, you omitted a formatted variable?

To run the tests:

1. Usually, you create a virtual Python environment and perform your tests in that one.

2. Upon creating the environment, you could try installing neomodel to it directly. I usually take the following steps:
    1. Create the environment
    2. `pip install ipython pytest shapely` # Notice the `pytest` package right here.
    3. In the directory that neomodel's `setup.py` file is, run `pip install ./ -e`
        * This step will install `neomodel` in such a way that any changes you apply to its code will be immediately available to any code (anywhere within that environment) that uses `neomodel`.

At the end of this process, go to the same directory that neomodel's `setup.py` directory is and type `pytest`.

Many thanks again for taking the time to look into these issues anyway.

**Comment by JVemmer** [comment]
@aanastasiou
I located the problem; was a bit too heavy handed in my replacements (mistook a format string for a params call). That is fixed now, and the tests all passed on my local machine. However, looking at the travis-ci tests being run here, there appeared a segfault at one of the tests? Unsure if that is code-related, or related to the travis setup itself.

**Comment by aanastasiou** [comment]
@JVemmer I understand, thank you very much, will take a look at this soon.

**Comment by JVemmer** [comment]
Hi @aanastasiou,
I kept getting confused about which branch I was dealing with, as well as which issue I was trying to solve, while trying fix the various issues I found. So I have made a decision to combine everything into a single pull request instead, so we both only have to look at a single thing, instead of the current 3 (which would have reached ~10 if everything was submitted individually). I will close this pull request to avoid confusion, and open up a single new one.

**Pull request closed without merging**
