### PR TITLE
support native neo4j datetime type

### PR DESCRIPTION
**Pull request by yeus**
Made this little patch in order to support native neo4j datetime format https://neo4j.com/docs/api/python-driver/current/temporal_types.html#neo4j.time.DateTime.

here is the documentation about this format. I used some functions that don't appear in the official documentation. especially:

`neo4j.to_native()`

I also don't know the neomodel policy about where to import the neo4j library.

### CODE REVIEW

**Comment by whatSocks** [comment]
Hello - thank you for your contribution. We are working on updating this repo and reviewing PRs but, to set expectations, maintenance is moving at a slow pace.

**Review by ficast — CHANGES_REQUESTED** [review]
@yeus can you add a test for this? Take a look on `test/test_properties.py ` for examples. Sorry about the delay, and thanks for that!

- [ ] add unit test

**Comment by yeus** [comment]
> @yeus can you add a test for this? Take a look on `test/test_properties.py ` for examples. Sorry about the delay, and thanks for that!
> 
>     * [ ]  add unit test

will do!

**Comment by aanastasiou** [comment]
Hello @yeus , do you think that this could also potentially address #610 too?

**Comment by yeus** [comment]
> Hello @yeus , do you think that this could also potentially address #610 too?

It kind of looks like that could be the case. to be sure I would test it though...

**Review by mariusconjeaud — CHANGES_REQUESTED** [review]
Add some tests

**Comment by mariusconjeaud** [comment]
Replaced by #811

**Pull request closed without merging**
