### PR TITLE
Consolidation of exceptions

### PR DESCRIPTION
**Pull request by funkyfuture**
nothing fancy, just a cleanup.

### CODE REVIEW

**Comment by robinedwards** [comment]
@funkyfuture thanks for this, id be happy to merge but can you fix the tests

**Comment by funkyfuture** [comment]
@robinedwards before i investigate what's wrong with the text against older Python versions, i'd like to know if the functionality of pickling exceptions is really needed. i haven't seen such before, and i can't imagine a usage scenario.

**Comment by funkyfuture** [comment]
i'm good with it now.

**Comment by robinedwards** [comment]
Thank you!

**Pull request merged**
